### ISSUE TITLE
Cannot add

### ISSUE THREAD

**Issue by bhuebschen** [lululombard/tesmart-lan-homeassistant#30]
## Version of the custom_component

Commit #81dfaef

## Configuration

```yaml
There is no documentation about a manual configuration
```

## Describe the bug

Cannot add the extension to home assistant ... and there is no documentation how to add... the existing docs are from the sample and are not applicable

**Comment by lululombard** [comment]
Hello, yes sorry, here's a `configuration.yaml` example: 
```yaml
media_player:
  - platform: tesmart_kvm
    kvms:
      kvm_1:
        friendly_name: KVM 1
        host: 10.10.10.1
      kvm_2:
        friendly_name: KVM 2
        host: 10.10.10.2
```
