### ISSUE TITLE
Integration Not Actually Selecting Source on 8-Port HDMI Switch

### ISSUE THREAD

**Issue by barndawgie** [lululombard/tesmart-lan-homeassistant#41]
## Version of the custom_component

0.0.2 form HACS

## Configuration

```yaml
---
media_player:
  - platform: tesmart_lan
    lans:
      tesmart_hdmi_switch:
        friendly_name: TV Room HDMI Switch
        host: !secret hdmi_switch_host
        sources:
          HDMI 1: Fire TV
          HDMI 2: Apple TV
          # HDMI 3: Nintendo N64
          # HDMI 4: Wii U
          # HDMI 5: HDMI 5
          # HDMI 6: Xbox One
          # HDMI 7: HDMI 7
          # HDMI 8: Sega Genesis
```

## Describe the bug

The integration is connecting successfully, because I can change the Mute/Unmute setting (and hear a beep when doing so), but choosing `Apple TV` or `Fire TV` from the drop-down on the entity page does nothing.

## Debug log

Even with debug logging enabled, nothing shows up in the logs when I (successfully) change the Mute setting or (unsuccessfully) change the HDMI input.
